services:
  web:
    build:
      context: .
      target: prod
    volumes:
      - .:/app
    ports:
      - "80:3000"
    environment:
      RAILS_ENV: production
  test:
    build:
      context: .
      target: test
    command: rspec
