version: 0.2

pases:
  install:
    runtime-versions:
      ruby: 3.0.5
    pre_build:
      commands:
      - echo 'Installing bundler' 
      - gem install bundler -v 2.4.3
      - echo 'Running bundle'
      - bundle install
    build:
      commands:
        - echo 'Running specs'
        - rspec
